/* =========================================================
   Internhub — Demo Data
   Stands in for the MongoDB/Express API for this frontend-only
   build. Structured the same way the real API would respond,
   so swapping in real fetch() calls later is a small change.
   ========================================================= */

const COMPANIES = [
  { id: "c1", name: "NovaTech", industry: "Software Development", location: "Bengaluru", size: "201-500", description: "NovaTech builds developer tooling used by fast-growing product teams across India.", website: "https://novatech.example.com" },
  { id: "c2", name: "CodeSphere", industry: "Software Development", location: "Pune", size: "51-200", description: "CodeSphere is a product studio partnering with startups to ship web and mobile apps.", website: "https://codesphere.example.com" },
  { id: "c3", name: "FinEdge", industry: "Finance", location: "Mumbai", size: "500-1000", description: "FinEdge builds lending and payments infrastructure for small businesses.", website: "https://finedge.example.com" },
  { id: "c4", name: "PixelWorks", industry: "UI/UX Design", location: "Hyderabad", size: "11-50", description: "PixelWorks is a design-first agency crafting digital products for consumer brands.", website: "https://pixelworks.example.com" },
  { id: "c5", name: "CloudNexa", industry: "Cybersecurity", location: "Delhi", size: "201-500", description: "CloudNexa secures cloud infrastructure for enterprises across South Asia.", website: "https://cloudnexa.example.com" },
  { id: "c6", name: "BrightLabs", industry: "Data Science", location: "Chennai", size: "51-200", description: "BrightLabs turns raw data into decisions for retail and logistics companies.", website: "https://brightlabs.example.com" },
];

const JOBS = [
  { id: "j1", title: "Frontend Developer", company: "c1", location: "Bengaluru", jobType: "Full Time", category: "Software Development", experience: "1-3 years", salary: "₹8L – ₹12L/year", skills: ["JavaScript", "React", "CSS"], isInternship: false, postedDaysAgo: 2, description: "Build and maintain customer-facing interfaces for NovaTech's developer dashboard.", responsibilities: ["Ship UI features in weekly sprints", "Collaborate with design on new flows", "Write maintainable, tested code"], requirements: ["1-3 years building web interfaces", "Strong CSS and JavaScript fundamentals", "Comfortable with Git workflows"], benefits: ["Health insurance", "Flexible hours", "Learning stipend"], deadline: "2026-11-15" },
  { id: "j2", title: "Backend Engineer (Node.js)", company: "c1", location: "Bengaluru", jobType: "Full Time", category: "Software Development", experience: "2-4 years", salary: "₹10L – ₹16L/year", skills: ["Node.js", "Express", "MongoDB"], isInternship: false, postedDaysAgo: 5, description: "Own API services powering NovaTech's core product.", responsibilities: ["Design REST APIs", "Optimize database queries", "Mentor junior engineers"], requirements: ["Experience with Node.js and Express", "Working knowledge of MongoDB", "Understanding of REST API design"], benefits: ["Health insurance", "Remote-friendly", "Annual bonus"], deadline: "2026-11-20" },
  { id: "j3", title: "Full Stack Developer", company: "c2", location: "Pune", jobType: "Full Time", category: "Software Development", experience: "1-3 years", salary: "₹7L – ₹11L/year", skills: ["JavaScript", "Node.js", "MongoDB"], isInternship: false, postedDaysAgo: 1, description: "Work across the stack building client web apps at CodeSphere.", responsibilities: ["Build features end-to-end", "Work directly with clients", "Ship to production weekly"], requirements: ["Comfortable with both frontend and backend", "Portfolio of shipped projects", "Good communication skills"], benefits: ["Performance bonus", "5-day work week"], deadline: "2026-11-10" },
  { id: "j4", title: "Data Analyst", company: "c6", location: "Chennai", jobType: "Full Time", category: "Data Science", experience: "0-1 years", salary: "₹5L – ₹8L/year", skills: ["SQL", "Python", "Excel"], isInternship: false, postedDaysAgo: 6, description: "Analyze retail datasets to support BrightLabs' client recommendations.", responsibilities: ["Build dashboards", "Clean and model datasets", "Present findings to clients"], requirements: ["Strong SQL skills", "Basic Python for data work", "Attention to detail"], benefits: ["Mentorship program", "Health insurance"], deadline: "2026-11-25" },
  { id: "j5", title: "UI/UX Designer", company: "c4", location: "Hyderabad", jobType: "Full Time", category: "UI/UX Design", experience: "1-3 years", salary: "₹6L – ₹10L/year", skills: ["Figma", "Prototyping", "User Research"], isInternship: false, postedDaysAgo: 3, description: "Design product experiences for PixelWorks' consumer clients.", responsibilities: ["Run user research sessions", "Design high-fidelity prototypes", "Partner with engineering on handoff"], requirements: ["Portfolio showing product design work", "Proficiency in Figma", "Understanding of accessibility basics"], benefits: ["Creative freedom", "Design conference budget"], deadline: "2026-11-18" },
  { id: "j6", title: "Security Analyst", company: "c5", location: "Delhi", jobType: "Full Time", category: "Cybersecurity", experience: "2-4 years", salary: "₹9L – ₹14L/year", skills: ["Network Security", "SIEM", "Python"], isInternship: false, postedDaysAgo: 8, description: "Monitor and respond to security incidents for CloudNexa's enterprise clients.", responsibilities: ["Triage security alerts", "Run vulnerability assessments", "Document incident reports"], requirements: ["Understanding of network security fundamentals", "Familiarity with SIEM tools", "Certification is a plus"], benefits: ["On-call allowance", "Health insurance"], deadline: "2026-11-22" },
  { id: "j7", title: "Financial Analyst", company: "c3", location: "Mumbai", jobType: "Full Time", category: "Finance", experience: "1-3 years", salary: "₹7L – ₹11L/year", skills: ["Excel", "Financial Modeling", "SQL"], isInternship: false, postedDaysAgo: 4, description: "Support lending decisions with financial modeling at FinEdge.", responsibilities: ["Build financial models", "Analyze credit risk data", "Report to senior analysts"], requirements: ["Strong Excel skills", "Understanding of financial statements", "Detail-oriented"], benefits: ["Performance bonus", "Health insurance"], deadline: "2026-11-12" },
  { id: "j8", title: "Marketing Associate", company: "c2", location: "Pune", jobType: "Full Time", category: "Marketing", experience: "0-1 years", salary: "₹4L – ₹6L/year", skills: ["Content Writing", "SEO", "Social Media"], isInternship: false, postedDaysAgo: 9, description: "Grow CodeSphere's inbound marketing channels.", responsibilities: ["Write blog and landing page content", "Manage social media calendar", "Track campaign performance"], requirements: ["Strong writing skills", "Basic SEO knowledge", "Comfortable with analytics tools"], benefits: ["Flexible hours", "5-day work week"], deadline: "2026-11-14" },
  { id: "j9", title: "HR Executive", company: "c1", location: "Remote", jobType: "Full Time", category: "Human Resources", experience: "1-3 years", salary: "₹5L – ₹8L/year", skills: ["Recruitment", "Onboarding", "HRMS"], isInternship: false, postedDaysAgo: 7, description: "Manage hiring and onboarding for NovaTech's growing team.", responsibilities: ["Coordinate interviews", "Run onboarding sessions", "Maintain HR records"], requirements: ["Experience in recruitment coordination", "Organized and detail-oriented", "Good interpersonal skills"], benefits: ["Remote work", "Health insurance"], deadline: "2026-11-19" },
  { id: "j10", title: "Product Manager", company: "c4", location: "Hyderabad", jobType: "Full Time", category: "Product", experience: "2-4 years", salary: "₹12L – ₹18L/year", skills: ["Roadmapping", "User Research", "Analytics"], isInternship: false, postedDaysAgo: 10, description: "Own the roadmap for one of PixelWorks' client products.", responsibilities: ["Define product roadmap", "Work with design and engineering", "Analyze product metrics"], requirements: ["Experience shipping digital products", "Comfortable with data-informed decisions", "Strong communication skills"], benefits: ["Stock options", "Health insurance"], deadline: "2026-11-28" },

  { id: "i1", title: "Frontend Developer Intern", company: "c1", location: "Bengaluru", jobType: "Internship", category: "Software Development", experience: "0-1 years", salary: "₹15k – ₹25k/month", skills: ["JavaScript", "React", "Node.js"], isInternship: true, postedDaysAgo: 2, description: "Support the NovaTech frontend team building new dashboard features.", responsibilities: ["Build small UI features under mentorship", "Fix bugs and write tests", "Join daily standups"], requirements: ["Basic JavaScript and HTML/CSS knowledge", "Currently pursuing a degree in CS or related field", "Eagerness to learn"], benefits: ["Certificate of completion", "Mentorship", "Pre-placement offer potential"], deadline: "2026-11-08" },
  { id: "i2", title: "Data Science Intern", company: "c6", location: "Chennai", jobType: "Internship", category: "Data Science", experience: "0-1 years", salary: "₹12k – ₹20k/month", skills: ["Python", "Pandas", "SQL"], isInternship: true, postedDaysAgo: 1, description: "Assist BrightLabs' analytics team with data cleaning and reporting.", responsibilities: ["Clean and prepare datasets", "Build basic visualizations", "Support senior analysts"], requirements: ["Familiarity with Python and Pandas", "Basic statistics knowledge", "Strong attention to detail"], benefits: ["Certificate of completion", "Letter of recommendation"], deadline: "2026-11-05" },
  { id: "i3", title: "UI/UX Design Intern", company: "c4", location: "Hyderabad", jobType: "Internship", category: "UI/UX Design", experience: "0-1 years", salary: "₹10k – ₹18k/month", skills: ["Figma", "Wireframing"], isInternship: true, postedDaysAgo: 3, description: "Support PixelWorks designers on client wireframes and prototypes.", responsibilities: ["Create wireframes", "Assist with user research", "Prepare design assets"], requirements: ["Basic Figma knowledge", "A portfolio or coursework samples", "Attention to visual detail"], benefits: ["Certificate of completion", "Portfolio-ready projects"], deadline: "2026-11-09" },
  { id: "i4", title: "Marketing Intern", company: "c2", location: "Pune", jobType: "Internship", category: "Marketing", experience: "0-1 years", salary: "₹8k – ₹15k/month", skills: ["Content Writing", "Social Media"], isInternship: true, postedDaysAgo: 4, description: "Help CodeSphere plan and publish content across channels.", responsibilities: ["Draft social posts", "Support campaign tracking", "Research content ideas"], requirements: ["Good writing skills", "Interest in marketing", "Basic social media familiarity"], benefits: ["Certificate of completion", "Flexible hours"], deadline: "2026-11-06" },
  { id: "i5", title: "Cybersecurity Intern", company: "c5", location: "Delhi", jobType: "Internship", category: "Cybersecurity", experience: "0-1 years", salary: "₹12k – ₹20k/month", skills: ["Networking", "Linux"], isInternship: true, postedDaysAgo: 6, description: "Shadow CloudNexa's security team and assist with monitoring tasks.", responsibilities: ["Monitor security dashboards", "Document findings", "Assist with basic audits"], requirements: ["Basic networking knowledge", "Familiarity with Linux", "Curiosity about security"], benefits: ["Certificate of completion", "Mentorship"], deadline: "2026-11-11" },
  { id: "i6", title: "Finance Intern", company: "c3", location: "Mumbai", jobType: "Internship", category: "Finance", experience: "0-1 years", salary: "₹10k – ₹16k/month", skills: ["Excel", "Financial Modeling"], isInternship: true, postedDaysAgo: 5, description: "Support FinEdge's analyst team with data entry and modeling tasks.", responsibilities: ["Update financial models", "Assist with report preparation", "Organize data records"], requirements: ["Strong Excel basics", "Pursuing a degree in finance or commerce", "Detail-oriented"], benefits: ["Certificate of completion", "Stipend"], deadline: "2026-11-07" },
  { id: "i7", title: "Product Intern", company: "c4", location: "Remote", jobType: "Internship", category: "Product", experience: "0-1 years", salary: "₹10k – ₹18k/month", skills: ["Research", "Analytics"], isInternship: true, postedDaysAgo: 8, description: "Support product managers with research and roadmap documentation.", responsibilities: ["Conduct competitor research", "Summarize user feedback", "Support sprint planning"], requirements: ["Strong communication skills", "Interest in product management", "Comfortable with spreadsheets"], benefits: ["Certificate of completion", "Remote flexibility"], deadline: "2026-11-16" },
  { id: "i8", title: "HR Intern", company: "c1", location: "Bengaluru", jobType: "Internship", category: "Human Resources", experience: "0-1 years", salary: "₹8k – ₹14k/month", skills: ["Recruitment", "Communication"], isInternship: true, postedDaysAgo: 9, description: "Support NovaTech's HR team with recruitment coordination.", responsibilities: ["Schedule interviews", "Maintain candidate records", "Assist with onboarding"], requirements: ["Good organizational skills", "Interest in HR", "Comfortable with spreadsheets"], benefits: ["Certificate of completion", "Mentorship"], deadline: "2026-11-13" },
];

const CATEGORIES = [
  { name: "Software Development", count: 4 },
  { name: "Data Science", count: 2 },
  { name: "UI/UX Design", count: 2 },
  { name: "Marketing", count: 2 },
  { name: "Finance", count: 2 },
  { name: "Human Resources", count: 2 },
  { name: "Product", count: 2 },
  { name: "Cybersecurity", count: 2 },
];

/** Demo accounts — for the assignment prototype only. Passwords are not real secrets. */
const DEMO_ACCOUNTS = [
  { email: "student@internhub.demo", password: "student123", role: "student", name: "Ananya Rao" },
  { email: "employer@internhub.demo", password: "employer123", role: "employer", name: "Rahul Mehta" },
];

function getCompanyById(id) {
  return COMPANIES.find((c) => c.id === id);
}
function getJobById(id) {
  return JOBS.find((j) => j.id === id);
}
